// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Studyzone.Infrastructure.Persistence;

#nullable disable

namespace Studyzone.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425012000_RemoveBatchSections")]
    public partial class RemoveBatchSections
    {
    }
}
